### PR TITLE
fix: support 'to' addresses with subjects

### LINKED ISSUE #998: Clear addresses from Mail (Personalization) object
I have a scenario where I would like to re-use the a Mail object but change the subject and to address. 

I only see methods for adding to already set emails. I do not see any methods for replacing or clearing the already set email addresses. 

It would be nice if there was a way to modify the addressees so that a Mail object could be reused.

### PR DESCRIPTION
**Pull request by childish-sambino**
If a specific 'to' address is "personalized" (contains substitutions or a subject), it should be in a new personalization object since a single personalization object cannot contain mixed substitutions or subjects.

Fixes #998

### CODE REVIEW

File: lib/mail/Mail.php [hunk 1]
```diff
@@ -109,26 +109,20 @@ public function __construct(
...
             $subjectCount = 0;
-            $personalization = new Personalization();
             foreach ($to as $email) {
-                if ($email->getSubstitutions()) {
+                if (\is_array($subject) || $email->isPersonalized()) {
                     $personalization = new Personalization();
+                    $this->addTo($email, null, null, null, $personalization);
+                } else {
+                    $this->addTo($email);
+                    $personalization = \end($this->personalization);
```
Comment (thinkingserious) [inline lib/mail/Mail.php:118]: Nice!

File: lib/mail/Mail.php [hunk 2]
```diff
@@ -109,26 +109,20 @@ public function __construct(
                 $to = [$to];
             }
             $subjectCount = 0;
-            $personalization = new Personalization();
             foreach ($to as $email) {
-                if ($email->getSubstitutions()) {
+                if (\is_array($subject) || $email->isPersonalized()) {
```
Comment (thinkingserious) [inline lib/mail/Mail.php:113]: nit: for consistency, all `is_array` function uses should be `\is_array`.

**Comment by Andrewsuares** [comment]
Hello,

I am looping emails from a database. I've set the $tos as an array.
$tos[] = [new \SendGrid\Mail\To($row['to'],)];

Now I get this error. 
Fatal error: Uncaught Error: Call to a member function isPersonalized() on array

**Comment by childish-sambino** [comment]
@Andrewsuares You're setting `tos` to an array of arrays to `To`s? I'm not sure how this even worked before these changes. Can you provide more example code in a new issue?
