### PR TITLE
fix: allow a float type as a substitution value in transactional templates

### LINKED ISSUE #861: Floats in macros
#### Issue Summary

When using transactional templates, you cannot inject floats or doubles.

#### Steps to Reproduce

- Create transactional template.
- Attempt to substitute macro value with a double or float.

#### Suggested Fix:

In this file: https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Substitution.php replace the is_int check on line 87 with is_numeric.

Also, it would be nice if you returned the offending value key.

### PR DESCRIPTION
**Pull request by thinkingserious**
# Fixes #861 

A short description of what this PR does.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the master branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

### CODE REVIEW

File: lib/mail/Substitution.php [hunk 1]
```diff
@@ -69,15 +69,15 @@ public function getKey()
...
      *
      * @throws \SendGrid\Mail\TypeException
      * @return null
      */
     public function setValue($value)
     {
-        if (!is_string($value) && !is_array($value) && !is_object($value) &&!is_bool($value) &&!is_int($value)) {
-            throw new TypeException('$value must be of type string, array or object.');
+        if (!is_string($value) && !is_array($value) && !is_object($value) && !is_bool($value) && !is_numeric($value)) {
+            throw new TypeException("The value: '$value' must be of type string, array, object, bool, int or float.");
```
Comment (childish-sambino) [inline lib/mail/Substitution.php:80]: Drop the colon: `"The value '$value' ..`

And needs [oxford comma](https://www.lexico.com/definition/oxford_comma).

File: test/unit/SubstitutionTest.php [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+use SendGrid\Mail\Substitution;
+
+/**
+ * This file tests attachments.
+ *
+ * @package SendGrid\Tests\Unit
+ */
+class SubstitutionTest extends TestCase
+{
+    public function testSubstitutionSetValue() {
```
Comment (childish-sambino) [inline test/unit/SubstitutionTest.php:18]: Need a sad path test.

File: test/unit/SubstitutionTest.php [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+ * This file tests substitutions.
+ */
+namespace SendGrid\Tests\Unit;
+
+use PHPUnit\Framework\TestCase;
+use SendGrid\Mail\Attachment;
+use SendGrid\Mail\Substitution;
+
+/**
+ * This file tests attachments.
```
Comment (childish-sambino) [inline test/unit/SubstitutionTest.php:12]: No, it does not.

File: test/unit/SubstitutionTest.php [hunk 4]
```diff
@@ -0,0 +1,37 @@
+<?php
+/**
+ * This file tests substitutions.
+ */
+namespace SendGrid\Tests\Unit;
+
+use PHPUnit\Framework\TestCase;
+use SendGrid\Mail\Attachment;
```
Comment (childish-sambino) [inline test/unit/SubstitutionTest.php:8]: Don't think this is needed.

File: test/unit/SubstitutionTest.php [hunk 5]
```diff
@@ -0,0 +1,37 @@
+<?php
+/**
+ * This file tests substitutions.
+ */
```
Comment (childish-sambino) [inline test/unit/SubstitutionTest.php:4]: This is duplicated.

File: lib/mail/Substitution.php [hunk 6]
```diff
@@ -51,7 +51,7 @@ public function __construct($key = null, $value = null)
     public function setKey($key)
     {
         if (!is_string($key)) {
-            throw new TypeException('$key must be of type string.');
+            throw new TypeException("The key: '$key' must be of type string.");
```
Comment (childish-sambino) [inline lib/mail/Substitution.php:54]: Same about dropping colon.
